https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [5]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.45538222, 0.88721317, 0.82153768, 0.21595103],
       [0.87195637, 0.53168564, 0.02020151, 0.03129179],
       [0.08793208, 0.51225591, 0.08768134, 0.23232317]])

In [1]:
from numpy.random import normal 

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [6]:
#ndarray,陣列運算
normal_value * 20

array([[-28.0174056 ,  24.3535129 , -10.18118589,   3.3599039 ],
       [ 23.45091008,  21.94480683,  10.12414691, -24.31409233],
       [  6.98129669,  -2.00537596, -18.88143264, -14.36754107]])

In [7]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([-0.52425873,  1.56028857, -1.41365265])